version: "3.8"
services:
  openvscode-server:
    image: lscr.io/linuxserver/openvscode-server:1.93.1-ls142
    container_name: openvscode-server
    environment:
      - PUID=1701
      - PGID=1702
      - TZ=America/Chicago
    volumes:
      - /mnt/apps01/docker/openvscode-server/config:/config
      - /mnt/apps01/stacks:/stacks
    ports:
      - 3000:3000
    restart: unless-stopped
networks: {}
