services:
  caddy:
    build:
      context: .
      dockerfile: Containerfile
    user: 568:1702
    environment:
      - umask=002
    restart: unless-stopped
    command: caddy run -c /Caddyfile
    env_file: .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/Caddyfile
      - /mnt/apps01/docker/caddy/config:/config
      - /mnt/apps01/docker/caddy/data:/data
    networks:
      - proxy-net
networks:
  proxy-net:
    name: proxy-net
    driver: bridge
    external: true
